### PR TITLE
 Use System.Numerics.BigInteger by adding System.Numerics.dll to the SDK 

### PR DESCRIPTION
**Pull request by ZimM-LostPolygon**
See https://github.com/loomnetwork/unity3d-sdk/issues/27

### CODE REVIEW

**Comment by enlight** [comment]
BigInteger changes look OK, but why is the events test in this PR?

**Comment by ZimM-LostPolygon** [comment]
Ah, haven't noticed that when committing, sorry. Is that a problem?

**Comment by enlight** [comment]
It interferes with reviewing the PRs, can you move the event tests to a separate PR?

**Comment by ZimM-LostPolygon** [comment]
Done

**Pull request merged**
