### PR TITLE
Refactored Address to not be a partial class of Protobuf Address class

### PR DESCRIPTION
**Pull request by ZimM-LostPolygon**
`Address` was the only Protobuf class from the SDK that was supposed to be used by end-users. Generally, this should not happen - Protobuf stuff is too low-level, and there's a reason why Protobuf classes are `sealed` - they are not supposed to be extended in any way. It was also quite annoying to see Protobuf-related methods in autocomplete when working with addresses.

This PR basically adds a nicer `Address` struct and hides all Protobuf stuff away from end users' eyes.

Noteworthy:
- Public interface remained unchanged.
- This change would allow to use `Address` directly when encoding/decoding EVM data with Nethereum, instead of using plain strings. It is currently quite annoying to juggle between `Address` and pure `string` representations of the same thing. This will make the usage patterns more uniform.
- Local address hex string is now checksum-encoded.
- `Address` instances can now be compared using `==` and `!=` operators for convenience.
- New implementation is slightly faster due to being a `struct`.
- `Debug.Log(address);` now actually logs the address string
- Since no Protobuf classes are now used publicly, they were moved in a separate namespace as to not clutter the autocompletion for end users.

### CODE REVIEW

**Comment by enlight** [comment]
Very nice! Did you test `AddressJsonConverter` in WebGL?

**Comment by ZimM-LostPolygon** [comment]
I didn't. What's specific about it for WebGL?

**Comment by enlight** [comment]
Just the usual WebGL issues that crop up when symbols are stripped during the build. This looks safe enough though I suppose.

**Comment by ZimM-LostPolygon** [comment]
@enlight Ah. It's not just WebGL then, also iOS, and, optionally, Android and Desktop. But yes, this should be fine.

**Pull request merged**
